<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-A017994339/blob/main/A01794339_Modulo5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARREGLOS - VECTORES**

1D ARRAY

In [2]:
#La libreria NumPy se utiliza para el manejo adecuado de listas 

import numpy as np

a = np.array([1,2,3,4,5])
#puedes acceder a traves del indice
a[2]
#Son similares a las listas , solo que estos deben ser del mismo tipo d datos
#funciones - size -> regresa el tamaño del arreglo
a.size
#retorna las dimensiones del arreglo
a.ndim
#Se puede hacer slicing a traves de los indices
#retorna los elementos del arreglo de la posicion 2 a la 4 [3,4]
b = a[2:4]
b

#Se puede modificar el valor de un arreglo a traves del indice
#array([150,   2,   3,   4,   5])
a[0]=150



**Vectores** - operaciones básicas

In [17]:
u = np.array([1,0])
v = np.array([0,1])
#suma 
z = u+v
z
#multiplicar por una escalar (constante)
y = np.array([1,2])
nuevoVector = 2*y
nuevoVector

#multiplicar 2 vectores
#array([2, 8])
x = np.array([2,4])
y = np.array([1,2])
xy = x*y
xy

#Producto punto
u= np.array([1,3])
v= np.array([2,3])
z = np.dot(u,v)
print(z)

#puedes agregar valores a todo el arreglo , por ejemplo sumar 5 a todo el arreglo
#array([ 6,  7,  8,  9, 10, 11])
a = np.array([1,2,3,4,5,6])
b = a+5
b

11


array([ 6,  7,  8,  9, 10, 11])

Funciones estadisticas

In [ ]:
#obtener la media aritmetica del arreglo
#5
a = np.array([1,3,5,7,9])
miMedia = a.mean()
miMedia

#Obtener la desviacion estandar
#2.8284271247461903
sd=a.std()
print(sd)
#Obtener el elemento mas grande
#9
maximo = a.max()
maximo


#retorna las dimensiones del arreglo
a.shape

2.8284271247461903


(5,)

Funciones de manipulación de datps

In [ ]:
#Linspace es util para generar valores entre dos puntos creando un nuevo arreglo con los valores
#array([-3.        , -2.33333333, -1.66666667, -1., -0.33333333,0.33333333,  1. ,  1.66666667,  2.33333333,  3. ])
valores = np.linspace(-3,3,num=10)
valores

#Arange -> permite crear conjuntos de datos 
#con un parametro crea una fila de datos, consecutivos entre 0 y 15
valoresGenerados = np.arange(15)
#ejemplo 2 
valoresGeneradosSeg = np.arange(5,15)
#ejemplo 3
valoresGeneradosTres = np.arange(-7.1,7)

#Vectores con ceros
#crea un vector con 5 elementos en cero
vCeros = np.zeros(5)

#Vectores con unos
#crea un vector con 5 elementos en unos
vUnos = np.ones(5)

**2D ARRAYS**

In [8]:
#matriz de 4 renglones x 2 columnas
A = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
A.ndim
A.shape
A.size

12

In [9]:
#acceder a los valores
#retorna el valor de 1
A[0,0]

#acceder a mas de un valor
#retorna los renglones 0,1 de la columna 2
A[0:2,2]

array([3, 5])

In [10]:
#convierte una lista a arreglo
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**API'S**

In [11]:
import requests
import os 
from PIL import Image
from IPython.display import IFrame

LECTURA DE PARAMETROS

In [14]:
url='https://www.ibm.com/'
r=requests.get(url)
r.status_code
print(r.request.headers)
print("request body:", r.request.body)

{'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=81B41F49724452041879A67B7367F217~-1~YAAQnxjdWMtHS6SDAQAArEKppQiQl4K45PyAjzJrygqorxHv8kslxElPlJy8TkwAjXkatsB2vdt+IE/RS5I+L7imdSy/ziBWN3zc1hvJJslB5UXDV6e52wf1NaEYrPtvBKN9qCKLjlDZmTvNrsFChhUpBDzDVoZJPS3e9jcdPEzWwQIidguueBTXIssIBYZhJI/bYOKdKRNgNtSRURlyuJWcgaOB3WFeUfVw2vzfYiM036HOh6JimiqrJkLERrvABJfiW5D0yy/WZnY3M0MZPgaciM0HK46OBc9VGlEa7W6CogK7mvyMv7373CxuFfAweC2usdn34dFOirz+4a/lfAbwwD1SRIMWzf6yijB8I+DTxLrDfLQ=~-1~-1~-1; bm_sz=EBE2DF453815516A8A8A63DE28A2F8F1~YAAQnxjdWMxHS6SDAQAArEKppRHk7i/8BAdouxicTufTArL6rWz8/56+Jv4+OKHsxpKnnzsWgIRNpZpx6N/SlNNmPkO+TL7bpedi4lryUTIyk+2+A33luuUpB5Y9Uacn5AQALegZY7SumZykwrrSJaZnjE85wrxSaIQPfuqMZ37SjwoI6nZjuAdWQFn4AouMl0s+S8gkC5YvJsZ7A4ChJMkrZk3HKJdQetxJtfFJnWSrJAyYCUsupEtUgIxlhr6jwumagSzZEHrj1k945PMnPtixOv/6KzDmJJAEbdriJFc=~3159093~4600631'}
request body: None


In [15]:
url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt'
path=os.path.join(os.getcwd(),'example1.txt')
r=requests.get(url)
with open(path,'wb') as f:
    f.write(r.content)